# Generated by Django 5.2.1 on 2025-06-02 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Store", "0005_alter_subcategoria_categoria_pai"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subcategoria",
            name="categoria_pai",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subcategorias",
                to="Store.categoria",
            ),
        ),
    ]
