# Generated by Django 5.2.1 on 2025-06-02 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Store", "0006_alter_subcategoria_categoria_pai"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="produto",
            name="categoria",
        ),
        migrations.AddField(
            model_name="produto",
            name="subcategoria",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="Store.subcategoria",
            ),
        ),
    ]
